// Package trails renders trails.json — the suggested reading-order artifact
// (ADR 0016). Each trail is a topologically-valid reading order for one weakly-
// connected component, rooted at the component's highest-PageRank document and
// preferring higher-authority docs among the available frontier (the modern
// realization of Vannevar Bush's associative "trails", "As We May Think", 1945).
//
// It is infrastructure: it reads the frozen emit.View (the domain Trails carried
// on the GraphMetrics) and never mutates the domain (ADR 0004). Output is
// deterministic: the trails are sorted by root upstream and the order within each
// is a deterministic priority topological sort, so the same corpus always yields
// byte-identical bytes. See docs/schemas/trails.schema.json for the contract.
package trails

import (
	"encoding/json"
	"fmt"

	"github.com/stacklok/matlatl/internal/domain/identity"
	"github.com/stacklok/matlatl/internal/infrastructure/emit"
)

// TrailsJSONName is the conventional trails.json filename.
const TrailsJSONName = "trails.json"

// SchemaVersion is the trails.json schema version. Additive fields are
// backward-compatible; renaming/removing a field bumps this. Mirrored by
// docs/schemas/trails.schema.json (a test validates emitted bytes against it).
const SchemaVersion = 1

// Document is the top-level trails.json shape. Field order is the wire order;
// every slice is sorted/deterministic.
type Document struct {
	SchemaVersion int     `json:"schemaVersion"`
	Tool          string  `json:"tool"`
	GeneratedNote string  `json:"generatedNote"`
	Trails        []Trail `json:"trails"`
}

// Trail is one weakly-connected component's reading order: its root (the
// cluster's most-important / highest-PageRank doc — an importance pointer, NOT
// necessarily the head of order) and the full topological reading sequence.
type Trail struct {
	Root  string   `json:"root"`
	Order []string `json:"order"`
}

const generatedNote = "Generated by matlatl. Suggested reading orders (associative trails, Bush 1945): " +
	"each trail is a topologically-valid order for one connected cluster, rooted at its most " +
	"important (highest-PageRank) document and preferring higher-authority docs among the available frontier."

// Build assembles the typed trails.json Document from the frozen View. A View
// with no trails yields a valid empty-but-stamped document.
func Build(v emit.View) Document {
	doc := Document{
		SchemaVersion: SchemaVersion,
		Tool:          "matlatl",
		GeneratedNote: generatedNote,
		Trails:        []Trail{},
	}
	for _, t := range v.Trails { // already sorted by Root
		doc.Trails = append(doc.Trails, Trail{
			Root:  t.Root.String(),
			Order: idStrings(t.Order),
		})
	}
	return doc
}

// JSON renders the View as the canonical trails.json bytes (pretty-printed,
// trailing newline). Deterministic: struct field order + sorted trails.
func JSON(v emit.View) ([]byte, error) {
	b, err := json.MarshalIndent(Build(v), "", "  ")
	if err != nil {
		return nil, fmt.Errorf("trails: marshal trails.json: %w", err)
	}
	return append(b, '\n'), nil
}

// idStrings renders a DocumentID slice as non-nil strings. It intentionally does
// NOT sort: the slice is the trail's reading ORDER, so its sequence is the
// payload — sorting it would destroy the meaning.
func idStrings(ids []identity.DocumentID) []string {
	out := make([]string, 0, len(ids))
	for _, id := range ids {
		out = append(out, id.String())
	}
	return out
}
